### ISSUE TITLE
FR: Check for path permissions outside of Termux directory?

### ISSUE THREAD

**Issue by RURon** [lekron42/samloader_termux#1]
Hello there! I just encountered the problem that after download and decryption the file could not be moved to /sdcard/Download/ as there was no access allowed. I had to google around a little to find out that Termux needs file access granted by Android by running "termux-setup-storage" - afterwards I could manually move the output file to /sdcard/Download/

Maybe you could implement a check for accessing the output dir - maybe it would be better to first ask the user for the output dir and check if you can access it (before starting the firmware download which takes some time...) and eventually display a hint for the termux-setup-storage (which only works for Termux of course) or something more general...

Just an idea, thanks for the nice script!

**Comment by lekron42** [comment]
Oh you're right, did not consider this. Will implement it in the next days. Thanks for your suggestion!

**Comment by lekron42** [comment]
Just uploaded a commit addressing this.
